Fix build workflow for flutter
AnonymusRaccoon/Aeris pull request #24
Opened 2022-01-26 17:41 UTC by Arthi-chaud

2022-01-26 17:43 UTC, 0Nom4D approved these changes

2022-01-27 08:22 UTC, AnonymusRaccoon approved these changes

2022-01-27 09:18 UTC, GitBluub requested changes
In build Apk - Debug you mv the profile and in the Build Apk - Release you mv the debug one

2022-01-29 15:38 UTC, GitBluub approved these changes

2022-02-10 11:21 UTC, Octopus773 approved these changes

2022-02-10 11:21 UTC, merged