Back with jwt auth and Get / Post on workflows
AnonymusRaccoon/Aeris pull request #37
Opened 2022-02-10 14:00 UTC by GitBluub

2022-02-10 14:36 UTC, Octopus773 requested changes
wesh wesh canne à peche

2022-02-10 14:36 UTC, Octopus773 commented on api/todo
> +- Crud pipelines
x

2022-02-10 15:10 UTC, AnonymusRaccoon commented on api/app/Main.hs
> +        connectionSettings = Connection.settings "localhost" 5432 "postgres" "password" "postgres"
You probably should not hardcode that

2022-02-11 12:59 UTC, Octopus773 approved these changes

2022-02-11 13:06 UTC, 0Nom4D approved these changes

2022-02-11 13:12 UTC, Arthi-chaud approved these changes

2022-02-11 13:13 UTC, Arthi-chaud reviewed
The code is not documented

2022-02-11 13:31 UTC, merged