Mobile client: Integrate backend (Basic)
AnonymusRaccoon/Aeris pull request #39
Opened 2022-02-12 13:25 UTC by Arthi-chaud

- create API interface
- Make the provider responsible from most of the api calls
- Fix some bugs

2022-02-13 20:14 UTC, 0Nom4D approved these changes

2022-02-13 20:18 UTC, 0Nom4D commented
### Note I forgot to write

As said to @Arthi-chaud, it might be more logic to put aeris_api.dart file inside a service folder instead of inside the model one:

* Api Service File isn't a model and belong to a service.

2022-02-14 10:06 UTC, AnonymusRaccoon commented on mobile/lib/src/providers/pipelines_provider.dart
> +  void setDisabledSplit(bool split) {
Use properties to do that, we don't want raw getter/setter. See [this](https://stackoverflow.com/questions/27683924/how-do-getters-and-setters-change-properties-in-dart) for more references.

2022-02-14 10:08 UTC, AnonymusRaccoon commented on mobile/lib/src/providers/pipelines_provider.dart
> +    _pipelineCollection.sortingMethod = sortingMethod;
Shouldn't you resort the collection here?

2022-02-14 10:20 UTC, AnonymusRaccoon commented on mobile/lib/src/views/pipeline_detail_page.dart
> +                            GetIt.I<AerisAPI>().updatePipeline(pipeline);
This won't work if the updatePipeline awaits before changing the state. You should not have unawaited calls in a state call.

2022-02-14 10:20 UTC, AnonymusRaccoon commented on mobile/lib/src/views/pipeline_detail_page.dart
> +                    GetIt.I<AerisAPI>().updatePipeline(pipeline);
Same issue.

2022-02-14 10:20 UTC, AnonymusRaccoon commented on mobile/lib/src/views/pipeline_detail_page.dart
> +                      GetIt.I<AerisAPI>().updatePipeline(pipeline);
Same issue.

2022-02-14 10:20 UTC, AnonymusRaccoon commented on mobile/lib/src/views/pipeline_detail_page.dart
> +                          GetIt.I<AerisAPI>().updatePipeline(pipeline);
Same issue.

2022-02-14 10:20 UTC, AnonymusRaccoon commented on mobile/lib/src/views/pipeline_detail_page.dart
> +                      GetIt.I<AerisAPI>().updatePipeline(pipeline);
Same issue.

2022-02-14 10:20 UTC, AnonymusRaccoon commented on mobile/lib/src/views/pipeline_detail_page.dart
> +                    GetIt.I<AerisAPI>().updatePipeline(pipeline);
Same issue.

2022-02-14 10:25 UTC, AnonymusRaccoon commented on mobile/lib/src/views/create_pipeline_page.dart
> +                                  .then((_) => setState(() {}));
I think you are doing something wrong.

2022-02-14 10:27 UTC, AnonymusRaccoon commented on mobile/lib/src/views/setup_action_page.dart
> +          GetIt.I<AerisAPI>().getActionsFor(serviceState!, widget.action).then((actions) => setState(() {
You should probably not run a setState in a setState, but I think the then is the right way

2022-02-14 10:27 UTC, AnonymusRaccoon commented on mobile/lib/src/views/setup_action_page.dart
> +          GetIt.I<AerisAPI>().getActionsFor(serviceState!, widget.action).then((actions) => setState(() {
You should probably not run a setState in a setState, but I think the then is the right way

2022-02-14 10:29 UTC, AnonymusRaccoon commented on mobile/lib/src/widgets/home_page_sort_menu.dart
>          collectionProvider.sortPipelines();
This should be done with the setter and not manually

2022-02-14 10:30 UTC, AnonymusRaccoon commented on mobile/lib/src/widgets/pipeline_card.dart
> +          ).then((_) => setState(() {}));
Weird

2022-02-14 10:30 UTC, AnonymusRaccoon commented on mobile/lib/src/widgets/pipeline_card.dart
> +          ).then((_) => setState(() {}));
Weird

2022-02-14 13:09 UTC, Arthi-chaud commented
The Comments @AnonymusRaccoon left were mainly because the name of the function 'updatePipeline" (now 'editPipeline') was unclear: the function takes a pipeline as parameters, and push its info to the API

2022-02-15 09:56 UTC, AnonymusRaccoon approved these changes

2022-02-15 09:57 UTC, GitBluub requested changes

2022-02-15 09:57 UTC, GitBluub commented on mobile/lib/src/models/reaction.dart
> +// ignore_for_file: hash_and_equals
Warning ignore ?

2022-02-15 09:57 UTC, GitBluub commented on mobile/lib/src/models/trigger.dart
> +// ignore_for_file: hash_and_equals
Warning ignore ?

2022-02-15 09:57 UTC, GitBluub commented on mobile/lib/src/models/trigger.dart
> +  // ignore: avoid_renaming_method_parameters
Do you need to ignore this warning too ?

2022-02-15 10:00 UTC, Octopus773 approved these changes

2022-02-15 10:01 UTC, GitBluub approved these changes

2022-02-15 10:01 UTC, merged