API: services .json
AnonymusRaccoon/Aeris pull request #66
Opened 2022-02-25 08:33 UTC by Arthi-chaud

2022-02-25 10:35 UTC, AnonymusRaccoon commented
How should the front display a name to the user and how should translations be handled?

2022-02-25 11:03 UTC, Octopus773 requested changes

2022-02-25 11:03 UTC, Octopus773 commented on api/services/youtube.json
> +					"description": "Date of the video like"
wth is this on `OnYtPlaylistAdd`, being on a playlist doesn't mean the video is liked

2022-02-25 11:03 UTC, Octopus773 commented on api/services/youtube.json
> +					"description": "Name of the channel the video was uploaded to"
```suggestion
					"description": "Name of the channel the video is belonging to"
```

2022-02-25 11:03 UTC, Octopus773 commented on api/services/youtube.json
> +					"description": "ID of the video to like"
```suggestion
					"description": "ID of the video to comment"
```

2022-02-25 21:09 UTC, Octopus773 approved these changes

2022-03-01 11:09 UTC, GitBluub approved these changes

2022-03-01 11:09 UTC, merged